// JavaScript for the search functionality

var simplemaps_countrymap_mapdata = {
  main_settings: {
    //General settings
    width: "700", //or 'responsive'
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#ffffff",
    pop_ups: "detect",

    //State defaults
    state_description: "State description",
    state_color: "#88A4BC",
    state_hover_color: "#3B729F",
    state_url: "",
    border_size: 1.5,
    all_states_inactive: "no",
    all_states_zoomable: "yes",

    //Location defaults
    location_description: "Location description",
    location_url: "",
    location_color: "#FF0067",
    location_opacity: 0.8,
    location_hover_opacity: 1,
    location_size: 25,
    location_type: "square",
    location_image_source: "frog.png",
    location_border_color: "#FFFFFF",
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",

    //Label defaults
    label_color: "#ffffff",
    label_hover_color: "#ffffff",
    label_size: 16,
    label_font: "Arial",
    label_display: "auto",
    label_scale: "yes",
    hide_labels: "no",
    hide_eastern_labels: "no",

    //Zoom settings
    zoom: "yes",
    manual_zoom: "yes",
    back_image: "no",
    initial_back: "no",
    initial_zoom: "-1",
    initial_zoom_solo: "yes",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.5,

    //Popup settings
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
    popup_nocss: "no",

    //Advanced settings
    div: "map",
    auto_load: "yes",
    url_new_tab: "no",
    images_directory: "default",
    fade_time: 0.1,
    link_text: "View Website",
  },
  state_specific: {
    AZABS: {
      name: "Abşeron",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZAGA: {
      name: "Ağstafa",
      description: "sa",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZAGC: {
      name: "Ağcabədi",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZAGM: {
      name: "Ağdam",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZAGS: {
      name: "Ağdaş",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZAGU: {
      name: "Ağsu",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZAST: {
      name: "Astara",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZBA: {
      name: "Bakı",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZBAB: {
      name: "Babək",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZBAL: {
      name: "Balakən",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZBAR: {
      name: "Bərdə",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZBEY: {
      name: "Beyləqan",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZBIL: {
      name: "Biləsuvar",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZCAB: {
      name: "Cəbrayıl",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZCAL: {
      name: "Cəlilabad",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZCUL: {
      name: "Culfa",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZDAS: {
      name: "Daşkəsən",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZFUZ: {
      name: "Füzuli",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZGA: {
      name: "Gəncə",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZGAD: {
      name: "Gədəbəy",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZGOR: {
      name: "Goranboy",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZGOY: {
      name: "Göyçay",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZGYG: {
      name: "Xanlar",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZHAC: {
      name: "Hajigabul",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZIMI: {
      name: "İmişli",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZISM: {
      name: "İsmayıllı",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZKAL: {
      name: "Kəlbəcər",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZKAN: {
      name: "Kangarli",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZKUR: {
      name: "Kürdəmir",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZLA: {
      name: "Lankaran City",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZLAC: {
      name: "Lachin",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZLAN: {
      name: "Lankaran",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZLER: {
      name: "Lerik",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZMAS: {
      name: "Masallı",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZMI: {
      name: "Mingəçevir",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZNA: {
      name: "Naftalan",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZNEF: {
      name: "Neftçala",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZNX: {
      name: "Naxçıvan",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZOGU: {
      name: "Oğuz",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZORD: {
      name: "Ordubad",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZQAB: {
      name: "Qəbələ",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZQAX: {
      name: "Qax",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZQAZ: {
      name: "Qazax",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZQBA: {
      name: "Quba",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZQBI: {
      name: "Qubadli",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZQOB: {
      name: "Qobustan",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZQUS: {
      name: "Qusar",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSA: {
      name: "Şəki",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSAB: {
      name: "Sabirabad",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSAD: {
      name: "Sədərək",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSAH: {
      name: "Şahbuz",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSAK: {
      name: "Şəki",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSAL: {
      name: "Salyan",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSAR: {
      name: "Şərur",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSAT: {
      name: "Saatlı",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSBN: {
      name: "Dəvəçi",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSIY: {
      name: "Siyəzən",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSKR: {
      name: "Şəmkir",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSM: {
      name: "Sumqayıt",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSMI: {
      name: "Şamaxı",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSMX: {
      name: "Samux",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSR: {
      name: "Shirvan",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZSUS: {
      name: "Şuşa",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZTAR: {
      name: "Tərtər",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZTOV: {
      name: "Tovuz",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZUCA: {
      name: "Ucar",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZXA: {
      name: "Stepanakert",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZXAC: {
      name: "Xaçmaz",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZXCI: {
      name: "Xocalı",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZXIZ: {
      name: "Xizı",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZXVD: {
      name: "Xocavənd",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZYAR: {
      name: "Yardımlı",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZYE: {
      name: "Yevlakh",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZYEV: {
      name: "Yevlakh Rayon",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZZAN: {
      name: "Zəngilan",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZZAQ: {
      name: "Zaqatala",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    AZZAR: {
      name: "Zərdab",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
  },
  locations: {
    0: {
      name: "Baku",
      lat: "40.395278",
      lng: "49.882222",
    },
  },
  labels: {
    AZABS: {
      name: "Abşeron",
      parent_id: "AZABS",
    },
    AZAGA: {
      name: "Ağstafa",
      parent_id: "AZAGA",
    },
    AZAGC: {
      name: "Ağcabədi",
      parent_id: "AZAGC",
    },
    AZAGM: {
      name: "Ağdam",
      parent_id: "AZAGM",
    },
    AZAGS: {
      name: "Ağdaş",
      parent_id: "AZAGS",
    },
    AZAGU: {
      name: "Ağsu",
      parent_id: "AZAGU",
    },
    AZAST: {
      name: "Astara",
      parent_id: "AZAST",
    },
    AZBA: {
      name: "Bakı",
      parent_id: "AZBA",
    },
    AZBAB: {
      name: "Babək",
      parent_id: "AZBAB",
    },
    AZBAL: {
      name: "Balakən",
      parent_id: "AZBAL",
    },
    AZBAR: {
      name: "Bərdə",
      parent_id: "AZBAR",
    },
    AZBEY: {
      name: "Beyləqan",
      parent_id: "AZBEY",
    },
    AZBIL: {
      name: "Biləsuvar",
      parent_id: "AZBIL",
    },
    AZCAB: {
      name: "Cəbrayıl",
      parent_id: "AZCAB",
    },
    AZCAL: {
      name: "Cəlilabad",
      parent_id: "AZCAL",
    },
    AZCUL: {
      name: "Culfa",
      parent_id: "AZCUL",
    },
    AZDAS: {
      name: "Daşkəsən",
      parent_id: "AZDAS",
    },
    AZFUZ: {
      name: "Füzuli",
      parent_id: "AZFUZ",
    },
    AZGA: {
      name: "Gəncə",
      parent_id: "AZGA",
    },
    AZGAD: {
      name: "Gədəbəy",
      parent_id: "AZGAD",
    },
    AZGOR: {
      name: "Goranboy",
      parent_id: "AZGOR",
    },
    AZGOY: {
      name: "Göyçay",
      parent_id: "AZGOY",
    },
    AZGYG: {
      name: "Xanlar",
      parent_id: "AZGYG",
    },
    AZHAC: {
      name: "Hajigabul",
      parent_id: "AZHAC",
    },
    AZIMI: {
      name: "İmişli",
      parent_id: "AZIMI",
    },
    AZISM: {
      name: "İsmayıllı",
      parent_id: "AZISM",
    },
    AZKAL: {
      name: "Kəlbəcər",
      parent_id: "AZKAL",
    },
    AZKAN: {
      name: "Kangarli",
      parent_id: "AZKAN",
    },
    AZKUR: {
      name: "Kürdəmir",
      parent_id: "AZKUR",
    },
    AZLA: {
      name: "Lankaran City",
      parent_id: "AZLA",
    },
    AZLAC: {
      name: "Lachin",
      parent_id: "AZLAC",
    },
    AZLAN: {
      name: "Lankaran",
      parent_id: "AZLAN",
    },
    AZLER: {
      name: "Lerik",
      parent_id: "AZLER",
    },
    AZMAS: {
      name: "Masallı",
      parent_id: "AZMAS",
    },
    AZMI: {
      name: "Mingəçevir",
      parent_id: "AZMI",
    },
    AZNA: {
      name: "Naftalan",
      parent_id: "AZNA",
    },
    AZNEF: {
      name: "Neftçala",
      parent_id: "AZNEF",
    },
    AZNX: {
      name: "Naxçıvan",
      parent_id: "AZNX",
    },
    AZOGU: {
      name: "Oğuz",
      parent_id: "AZOGU",
    },
    AZORD: {
      name: "Ordubad",
      parent_id: "AZORD",
    },
    AZQAB: {
      name: "Qəbələ",
      parent_id: "AZQAB",
    },
    AZQAX: {
      name: "Qax",
      parent_id: "AZQAX",
    },
    AZQAZ: {
      name: "Qazax",
      parent_id: "AZQAZ",
    },
    AZQBA: {
      name: "Quba",
      parent_id: "AZQBA",
    },
    AZQBI: {
      name: "Qubadli",
      parent_id: "AZQBI",
    },
    AZQOB: {
      name: "Qobustan",
      parent_id: "AZQOB",
    },
    AZQUS: {
      name: "Qusar",
      parent_id: "AZQUS",
    },
    AZSA: {
      name: "Şəki",
      parent_id: "AZSA",
    },
    AZSAB: {
      name: "Sabirabad",
      parent_id: "AZSAB",
    },
    AZSAD: {
      name: "Sədərək",
      parent_id: "AZSAD",
    },
    AZSAH: {
      name: "Şahbuz",
      parent_id: "AZSAH",
    },
    AZSAK: {
      name: "Şəki",
      parent_id: "AZSAK",
    },
    AZSAL: {
      name: "Salyan",
      parent_id: "AZSAL",
    },
    AZSAR: {
      name: "Şərur",
      parent_id: "AZSAR",
    },
    AZSAT: {
      name: "Saatlı",
      parent_id: "AZSAT",
    },
    AZSBN: {
      name: "Dəvəçi",
      parent_id: "AZSBN",
    },
    AZSIY: {
      name: "Siyəzən",
      parent_id: "AZSIY",
    },
    AZSKR: {
      name: "Şəmkir",
      parent_id: "AZSKR",
    },
    AZSM: {
      name: "Sumqayıt",
      parent_id: "AZSM",
    },
    AZSMI: {
      name: "Şamaxı",
      parent_id: "AZSMI",
    },
    AZSMX: {
      name: "Samux",
      parent_id: "AZSMX",
    },
    AZSR: {
      name: "Shirvan",
      parent_id: "AZSR",
    },
    AZSUS: {
      name: "Şuşa",
      parent_id: "AZSUS",
    },
    AZTAR: {
      name: "Tərtər",
      parent_id: "AZTAR",
    },
    AZTOV: {
      name: "Tovuz",
      parent_id: "AZTOV",
    },
    AZUCA: {
      name: "Ucar",
      parent_id: "AZUCA",
    },
    AZXA: {
      name: "Stepanakert",
      parent_id: "AZXA",
    },
    AZXAC: {
      name: "Xaçmaz",
      parent_id: "AZXAC",
    },
    AZXCI: {
      name: "Xocalı",
      parent_id: "AZXCI",
    },
    AZXIZ: {
      name: "Xizı",
      parent_id: "AZXIZ",
    },
    AZXVD: {
      name: "Xocavənd",
      parent_id: "AZXVD",
    },
    AZYAR: {
      name: "Yardımlı",
      parent_id: "AZYAR",
    },
    AZYE: {
      name: "Yevlakh",
      parent_id: "AZYE",
    },
    AZYEV: {
      name: "Yevlakh Rayon",
      parent_id: "AZYEV",
    },
    AZZAN: {
      name: "Zəngilan",
      parent_id: "AZZAN",
    },
    AZZAQ: {
      name: "Zaqatala",
      parent_id: "AZZAQ",
    },
    AZZAR: {
      name: "Zərdab",
      parent_id: "AZZAR",
    },
  },
};
